### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by knownasilya** [cibernox/ember-k-codemod#2]
Looks like most of the paths are hard coded in the bin file. They should use `path.join(..)` or `path.sep`.

Related issue https://github.com/abuiles/ember-watson/issues/110

**Comment by yogendra-atcs** [comment]
@cibernox 
Please have a look into above issue and resolve it for windows.
waiting for your response....

**Comment by cibernox** [comment]
I tried to fix it but I don't have a windows machine or VM to verify it. Can you install 0.1.5 and check if this is fixed?

**Comment by knownasilya** [comment]
I think one more spot needs changing https://github.com/cibernox/ember-k-codemod/blob/master/bin/ember-k-codemod.js#L25

**Comment by cibernox** [comment]
@knownasilya what about 0.1.6?

**Comment by yogendra-atcs** [comment]
@cibernox
Thanks for response but still giving error in windows...
**$ ember-k-codemod --empty
Error: spawn UNKNOWN**
    at exports._errnoException (util.js:1020:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:369:9)
    at Object.<anonymous> (C:\Users\Yogen\AppData\Roaming\npm\node_modules\ember-k-codemod\bin\ember-k-codemod.js:31:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

**Comment by cibernox** [comment]
@yogendra-atcs on what version of node are you? Perhaps node 4? I don't see a reason why spawn would fail on windows.

**Comment by yogendra-atcs** [comment]
Using below version
node: 6.11.2
npm: 3.10.10
ember-cli: 2.14.1
OS: Windows 10 Home, 64-bit

**Comment by knownasilya** [comment]
@cibernox this issue might help https://github.com/ember-cli/ember-modules-codemod/issues/13 which was fixed by https://github.com/ember-cli/ember-modules-codemod/pull/43/files
